#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'dm-core'
require 'dm-migrations'
require 'ApisDB'

opt = OpenStruct.new
opt.host = "sqlite:"
o = OptionParser.new
o.banner << " db-name"
o.on("-h ", "--host ", String, "db host (default #{opt.host})") {|h| opt.host = h}
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size != 1)
  STDERR << o
  exit(1)
end

db = ARGV.first

DataMapper.setup(:default, opt.host + db)
begin
  DataMapper.auto_migrate!
rescue
  STDERR << $! << "\n"
  STDERR << "I cannot create " << opt.host << db << ". Perhaps it's a permissions issue?\n"
end