#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'csv'

# add current directory to load path
$LOAD_PATH.unshift(File.dirname($0))
require 'ApisDB'

opt = OpenStruct.new
opt.storage = "misc_apis"
opt = ApisDB.loadOptions(opt)

o = OptionParser.new
o.banner << " csv"
begin
  o.on("-h ", "--host ", String, "database host (#{opt.host})") {|t| opt.host = t}
  o.on("-s ", "--storage ", String, "storage database (default #{opt.storage})") {|t| opt.storage = t}
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size != 1)
  STDERR << o
  exit(1)
end

csv, rest = ARGV

db = ApisDB.new(opt.host + "/" + opt.storage)

datasets = []
db.query("SELECT dataset FROM dataset").each do |row|
  datasets.push(row[0])
end

seen = Hash.new

CSV.foreach(csv, options = {:headers => true, :converters => :numeric}) do |row|
  if (!row["dataset"])
    STDERR << "No dataset for row starting with " << row.first << "...\n"
    next
  end
  if (!row["name"])
    row["name"] = row["site"] + "_" + row["filter"].to_s
  end
  datasets.grep(/#{row["dataset"]}/).each do |dataset|
    row.each do |pair|
      next if pair.first == "dataset" || pair.first.nil?
      printf("%s\t%s\t%s\n", dataset, pair.first.downcase, pair.last.to_s.gsub("\t",""))
      seen[dataset] = true
    end
  end
end

missing = datasets - seen.keys
missing.each do |dataset|
  STDERR << "Warning: no info for dataset " << dataset << "\n"
end
