#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'

# add current directory to load path
$LOAD_PATH.unshift(File.dirname($0))
require 'ApisDB'

opt = OpenStruct.new
opt.storage = "misc_apis"
opt.keep = false
ApisDB.loadOptions(opt)

ARGV.options do |opts|
  opts.banner << " [dataset... dataset...]"
  opts.on("-k", "--keep", "keep blast data (default #{opt.keep})") {opt.keep = true}
  opts.on("-s ", "--storage ", String, "storage database (default #{opt.storage})") {|t| opt.storage = t}
  opts.on("-h ", "--host ", String, "database host (default #{opt.host})") {|t| opt.host = t}
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
end

db = ApisDB.new(opt.host + "/" + opt.storage)

ARGV.each do |dataset|
  db.deleteDataset("dataset = '#{dataset.quote}'", opt.keep)
end
