#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'apis'

opt = OpenStruct.new
opt.all = false
opt.database = "phylodb"
opt.date = "1970-01-01"
opt.storage = "misc_apis"
opt.host = "mysql-lan-pro.jcvi.org"
opt.exclude = nil
opt.f = nil
opt.contig = nil
opt.ruleMaj = false

ARGV.options {|opts|
  opts.banner << " [dataset... dataset...]"
  opts.on("-a", "--all", "reprocess all datasets") {|t| opt.all = t}
  opts.on("-c ", "--contig ", String, 
         "only process contig supplied") {|t| opt.contig = t}
  opts.on("-d ", "--database ", String, 
         "query database (default #{opt.database})") {|t| opt.database = t}
  opts.on("-f ", "--file ", String, 
        "read exclusion for species from csv file") {|t| opt.f = t} 
  opts.on("-r", "--ruleMajority", "use majority classification") {opt.ruleMaj = true}
  opts.on("-s ", "--storage ", String, "storage database (default #{opt.storage})") {|t| opt.storage = t}
  opts.on("-t ", "--time ", String, "date string (year-month-day) to process after") {|t| opt.date = t}
  opts.on("-h ", "--host ", String, "database host (default #{opt.host})") {|t| opt.host = t}
  opts.on("-y ", "--exclude ", String,
	  "exclude taxonomy matching regexp from run") {|t| opt.exclude = t}
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1 && !opt.all)
    STDERR.puts opts
    exit(1)
  end
}

ex = Hash.new
if (opt.f)
  CSV.foreach(opt.f) {|row|
    ex[row.first] = row.last
  }
end

db = MyDB.new(opt.host, opt.storage, "apis", "apis_user", opt.database)
db.tax

if (opt.all)
  db.query("select dataset from dataset WHERE date_added > '#{opt.date}'").each {|dataset|
    ARGV.push(dataset[0])
  }
end

ARGV.each {|dataset|
  STDERR.printf("Reclassifying %s...\n", dataset)
  count = 0
  phrase = "tree WHERE dataset='#{dataset}'"
  phrase += " AND seq_name LIKE '%-#{opt.contig}'" if (opt.contig)
  STDERR.printf("Counting trees....\n")
  trees = db.count(phrase)
  query = "SELECT seq_name, tree FROM #{phrase}"
  first = true
  db.query(query).each {|row|
    if (first)
      STDERR.printf("Processing trees....\n")
      first = false
    end
    name, tree = row
    tree = NewickTree.new(tree)
    if (opt.f)
      sp = db.tax[name.split("-").last]["species"]
      exclude = ex[sp]
    end
    db.createClassification(tree, name, dataset, exclude, opt.ruleMaj)
    count += 1
    STDERR.printf("%4.2f%% done...\n", count*100.0/trees) if (count % 1000 == 0)
  }
}
