#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'ApisDB'

opt = OpenStruct.new
opt.everything = false
ApisDB.loadOptions(opt)
opt.database = opt.host + "/phylodb"

ARGV.options do |o|
  o.banner << " [contig-id...id...]"
  o.on("-d ", "--database ", String, 
         "query database (default #{opt.database})") {|d| opt.database = d}
  o.on("-e", "--everything", "write entire ComboDB") {opt.everything = true}  
  begin
    o.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts o
    exit(1)
  end
  if (ARGV.size < 1 && !opt.everything)
    STDERR.puts o
    exit(1)
  end
end

connectDB(opt.database)

if (opt.everything)
  contig_names = Contig.find(:all, :select=>"name")
else
  contig_names = ARGV
end

pep = File.new(opt.database.split("/").last + ".pep", "w")
Protein.includes(:contig).find_each(:conditions =>{:contig_name=>contig_names}) do |prot|
  pep.print prot.to_fasta
end
pep.close

