#!/usr/bin/env ruby

require 'optparse'
require 'rubygems'
require 'bio'
require 'date'
require 'ostruct'
require 'Phylogeny'

# add current directory to load path
$LOAD_PATH.unshift(File.dirname($0)+"../")

#check version of ruby
if (RUBY_VERSION < "1.9.2")
  STDERR << "Error: version of ruby on your path should be 1.9.2 or newer to run "
  STDERR << "APIS and its scripts. You are using the ruby in " << `which ruby`.chomp 
  STDERR << " which is only version " << RUBY_VERSION << ".\n"
  exit(1)
end

require 'apis'

opt = OpenStruct.new 
o = OptionParser.new

o.banner << " usedTaxa.tab"
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size < 1)
  STDERR << o
  exit(1)
end

tax, rest = ARGV

db = ApisDB.new(nil)
db.loadTaxonomy(nil, tax)
bad = false

thash = db.fullSpeciesTaxonomyHash
thash.keys.sort.each do |sp|
  tax = thash[sp].split("; ")
  if tax.size != 7
    print [db.taxid(sp).to_s, tax.size, thash[sp]].join("\t") + "\n"
    bad = true
  end
end

if (!bad)
  STDERR << "No bad taxonomies!\n"
end

